defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

################################# Default configuration ###################
baseURL = "https://aigcx.club/"
title = "中国AIGC产业联盟"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### Chinese Navigation ########################
[[Languages.zh.menu.main]]
name = "联盟"
url = "#about"
weight = 1

[[Languages.zh.menu.main]]
name = "规范"
url = "#services"
weight = 2

[[Languages.zh.menu.main]]
name = "专栏"
url = "#portfolio"
weight = 3

# [[Languages.zh.menu.main]]
# name = "成员展示"
# url = "#team"
# weight = 4

[[Languages.zh.menu.main]]
name = "顾问团及秘书处"
url = "#testimonial"
weight = 5

[[Languages.zh.menu.main]]
name = "资讯及活动"
url = "#blog"
weight = 6

# [[Languages.zh.menu.main]]
# name = "联系我们"
# url = "#contact"
# weight = 7

# [[Languages.zh.menu.main]]
# name = "themefisher"
# url = "https://themefisher.com/"
# weight = 8

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "about"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "Standards"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "Hotspot"
url = "#portfolio"
weight = 3

# Commented out the following code:
# [[Languages.en.menu.main]]
# name = "team"
# url = "#team"
# weight = 4

[[Languages.en.menu.main]]
name = "Advisory Group and Secretariat"
url = "#testimonial"
weight = 5

[[Languages.en.menu.main]]
name = "blog"
url = "#blog"
weight = 6

#[[Languages.en.menu.main]]
#name = "contact"
#url = "#contact"
#weight = 7


#[[Languages.en.menu.main]]
#name = "Dropdown"
#weight = 7
#hasChildren = true

#[[Languages.en.menu.main]]
#parent = "Dropdown"
#name = "Dropdown 1"
#url = "#"
#weight = 1

#[[Languages.en.menu.main]]
#parent = "Dropdown"
#name = "Dropdown 2"
#url = "#"
#weight = 2

#[[Languages.en.menu.main]]
#name = "themefisher"
#url = "https://themefisher.com/"
#weight = 8





############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "做困难但正确之事 把不可能变成可能"
author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
#[[params.social]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
#link = "#"




################################ Chinese Language ########################
[Languages.zh]
languageName = "简体中文"
languageCode = "zh"
contentDir = "content/chinese"
weight = 1
home = "主页"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"



################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 3
home = "Home"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"


